### ISSUE TITLE
wobbly on mac?

### ISSUE THREAD

**Issue by superon** [jaacksondev/etched#110]
[Forge 1.20.1] Etched 3.0.2

https://github.com/user-attachments/assets/ab026d1d-05ca-4d97-ad61-8c8ba9a260f1

[latest.log](https://github.com/user-attachments/files/16648084/latest.log)

**Comment by KILLKULA** [comment]
Hi, what kind of mac do you have and what version of macOS? I'm on Air m2 Sonoma 14.6.1 and I don't have this problem. Maybe it's a Java problem.

**Comment by superon** [comment]
hmm, likely mac poor ol' mac then: Mac Pro (Late 2013)

**Comment by Ocelot5836** [comment]
This usually happens when your internet is too slow to play a stream

**Comment by TemanSv1n** [comment]
This is not because of mac. I have encountered the same problem. I just have spent an hour to figure out how it works by comparing working audios and not-working. The result: system works properly only with STEREO audios like this

![Image](https://github.com/user-attachments/assets/7b95e51c-a7a7-450d-a71a-d670bf4db4b9)

and acts wobbly, as on video, with this

![Image](https://github.com/user-attachments/assets/06dca423-2dfc-4183-89b9-a2bfa289db22)

So the decision outside of the mod is to properly prepare files (in audacity just a few clicks, or with python script, i did that on my audio generating server), inside the mod - probably write a stereotizator.

**Comment by superon** [comment]
> This is not because of mac. I have encountered the same problem. I just have spent an hour to figure out how it works by comparing working audios and not-working. The result: system works properly only with STEREO audios like this
> 
> ![Image](https://github.com/user-attachments/assets/7b95e51c-a7a7-450d-a71a-d670bf4db4b9)
> 
> and acts wobbly, as on video, with this
> 
> ![Image](https://github.com/user-attachments/assets/06dca423-2dfc-4183-89b9-a2bfa289db22)
> 
> So the decision outside of the mod is to properly prepare files (in audacity just a few clicks, or with python script, i did that on my audio generating server), inside the mod - probably write a stereotizator.

are you saying i should set the audio to output as mono?  i can't believe i didn't try this already as part of my experimentation if that is what you're saying (if that is an option of course, this was now so long ago i can't remember if that's a thing)... the examples are streaming from radio services
