### ISSUE TITLE
Unsupported Content-Type: audio/mpeg; charset=UTF8

### ISSUE THREAD

**Issue by PTALTS-LK** [jaacksondev/etched#58]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
I tried burning music from 'music.163.com' in the etching table.
The result is "Unsupported Content-Type: audio/mpeg; charset=UTF8" error.
```

### latest.log

```shell
none
```

**Comment by PTALTS-LK** [comment]
![image](https://user-images.githubusercontent.com/62936489/222903292-a878c526-2f7a-43f9-b554-1910dfcc902e.png)
I used this link: http://music.163.com/song/media/outer/url?id=1874120860.mp3

**Comment by PTALTS-LK** [comment]
But this link can be played normally on the radio

**Comment by LuiCat** [comment]
Did a quick search, the bug is caused by this line:
https://github.com/MoonflowerTeam/etched/blob/d4771029027b87bfaf8ee522009aaf8a8211f29e/common/src/main/java/gg/moonflower/etched/common/menu/EtchingMenu.java#L179

Apparently http content types can have derivatives, thus need to be split when matching to the string table `VALID_FORMATS`.

I will try to do a local build and see if this fix works.
